In [ ]:
import numpy as np
print(np.sqrt(10))

In [5]:
x = [3,5,7,1,2]
print("minimum",np.amin(x))

minimum 1


In [7]:
print("maximum",np.amax(x))

maximum 7


#rounding off

In [9]:
print(np.ceil(34.86))

35.0


In [4]:
y =[5,10,15]
print(np.ceil(np.sum(np.sqrt(y))))


10.0


In [5]:
#declaring an array
xyz = np.array([5,8,13])
print(xyz)

[ 5  8 13]


In [18]:
print(type(xyz))

<class 'numpy.ndarray'>


In [20]:
xyz.dtype

dtype('int32')

In [21]:
b = np.asarray(xyz)

In [23]:
b

array([ 5,  8, 13])

In [24]:
print(b)

[ 5  8 13]


#datatype

In [28]:

my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("matrix\n", mat)

matrix
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
print(type(mat))

<class 'numpy.ndarray'>


In [29]:
print(mat.ndim)

2


#total no of elements in matrix

In [32]:
print(mat.size)

9


#number of element across each axis

In [37]:

print(mat.shape)

(3, 3)


In [35]:
print(mat.dtype)

int32


#arrange and line space

In [40]:
a = np.arange(2,10.5,4)#runs with numpy range(because of float)
a

array([ 2.,  6., 10.])

In [41]:
print(list(range(2,1)))# don't run with python range

TypeError: 'float' object cannot be interpreted as an integer

In [42]:
print(a[::-1])#revrse order

[10.  6.  2.]


In [52]:
b =np.linspace(10,40,5, endpoint = False, retstep = True) # 10 or 40 ke beech mein 5
print(b)

(array([10., 16., 22., 28., 34.]), 6.0)


genrate random function

In [55]:
np.random.seed(6)
print(np.random.rand(10,6))

[[0.89286015 0.33197981 0.82122912 0.04169663 0.10765668 0.59505206]
 [0.52981736 0.41880743 0.33540785 0.62251943 0.43814143 0.73588211]
 [0.51803641 0.5788586  0.6453551  0.99022427 0.8198582  0.41320093]
 [0.87626766 0.82375943 0.05447451 0.71863724 0.80217056 0.73640664]
 [0.70913175 0.54093685 0.12482417 0.9576473  0.4032563  0.21695116]
 [0.71727585 0.99420744 0.25561406 0.67130943 0.59900591 0.71733215]
 [0.93734953 0.35180977 0.2536341  0.40247251 0.74651072 0.72407057]
 [0.4061078  0.98937985 0.45049928 0.37380843 0.70962861 0.08245855]
 [0.39837292 0.77088097 0.76475098 0.28385938 0.18954219 0.47125096]
 [0.33480604 0.73473504 0.18910712 0.33110407 0.84422842 0.61502403]]


In [63]:
print(np.random.randn(10,3))

[[ 0.09079696  0.27026659 -0.31449183]
 [-0.14497558  0.35537056 -1.69891959]
 [ 0.65725757 -0.47237563 -3.69023566]
 [ 0.53384158 -1.20135139  0.89165273]
 [-0.98472793 -0.21062697  0.66615792]
 [-0.79624825 -0.99541982 -0.11412716]
 [ 1.37018152  1.09965334  1.40058146]
 [ 0.38470804  0.48828411  1.07030973]
 [ 0.5685534  -0.80496557  0.78263039]
 [-0.49341854 -0.81988596  0.13871369]]


In [57]:
print(np.random.randint(5,200,100))# seed will not work

[100  76 138  77  84  44 104 175  10  62 104 125 101  28 129  92  50 164
 149  40   7 104  19  25 130  34 190 133 107 195 104  23 102  93 165  76
 149 118 109  42  51  94 177 189 178 170  65 134 113 198 119  30  30 170
  21  73 187 199  17  54  52  19 129  99 159  69  96 135   7  69  44  16
  91  43 175 149  14 154  34 196 191  29 199  25  39 104  46  67  41  68
 196 181 132 138  31 172 102  38  43  63]


#program to genrate otp

In [3]:
otp = (np.random.randint(1000, 10000))
print(otp)

flag = 0
while (flag==0):
    
    otpin = int(input("Enter your otp"))
    if otpin == otp:
        print("your otp is correct :",otp)
        flag =1
        
    else:
        print("invalid otp")

8118
Enter your otp4563
invalid otp
Enter your otp8118
your otp is correct : 8118


In [8]:
c = aa.reshape(6,5)
c

array([[65, 50,  9, 33,  6],
       [ 8,  6, 27, 19, 79],
       [12, 89, 39, 96, 14],
       [93, 51,  3, 13, 11],
       [59, 79, 37, 89, 54],
       [69, 24, 96, 18, 93]])

In [9]:
print(c.min())

3


In [10]:
print(c.max())

96


In [12]:
import numpy as np
m = ri(1,100,25).reshape(5,5)
print(np.sort(m))

[[13 37 41 50 65]
 [ 7 16 84 84 91]
 [37 38 44 53 75]
 [11 32 46 52 93]
 [ 2 17 27 60 65]]


In [14]:
emp_salary = ri(8000,70000,10)
print(emp_salary)

[52725 65994 22063 69629 68598 28107 46783 53374 28333 24414]


In [20]:
print(emp_salary[np.where(emp_salary<25000)])

[22063 24414]


In [19]:
print(np.where(emp_salary<25000))

(array([2, 9], dtype=int64),)


In [21]:
np.clip(emp_salary,a_min = 20000,a_max=50000)

array([50000, 50000, 22063, 50000, 50000, 28107, 46783, 50000, 28333,
       24414])